name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  call-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'repository_dispatch') }}
    uses: Platform-System/Platform.CI-CD/.github/workflows/deploy-docker.yml@main
    with:
      service_name: platform-portal-ui
    secrets: inherit
