name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/build-nextjs.yml@main
    with:
      image_name: 'platform-portal-ui'
      push_image: true
      build_args: |
        NEXT_PUBLIC_API_URL=${{ vars.PUBLIC_API_URL }}
        NEXT_PUBLIC_KEYCLOAK_URL=${{ vars.PUBLIC_AUTH_URL }}
        NEXT_PUBLIC_KEYCLOAK_REALM=${{ vars.KEYCLOAK_REALM }}
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${{ vars.PORTAL_CLIENT_ID }}
